[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Ryocery"
name = "Abundance"
description = "Reduces grind by multipling resources and money. Configurable."
websiteUrl = "https://github.com/Ryocery/abundance-aeruta"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Aeruta = "6.0.741"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/InsanePhysics/release/com.github.ryocery.insanephysics.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[publish]
communities = [ "aeruta", ]

[publish.categories]
aeruta = [ "mods", ]